name        : aalib
version     : 1.4.0
release     : 4
source      :
    - http://ufpr.dl.sourceforge.net/project/aa-project/aa-lib/1.4rc5/aalib-1.4rc5.tar.gz : fbddda9230cf6ee2a4f5706b4b11e2190ae45f5eda1f0409dc4f99b35e0a70ee
homepage    : http://aa-project.sourceforge.net/aalib/
license     : LGPL-2.0
summary     : AAlib is an portable ascii art GFX library
description : |
    AAlib is an portable ascii art GFX library. It allows conversion of still and moving images into ASCII art, and allowing some programs like media players to output in text mode.
patterns   :
    - devel: /usr/share/aclocal/aalib.m4
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
